"""initial

Revision ID: b815f1b34939
Revises: 
Create Date: 2026-07-27 16:54:16.682249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b815f1b34939'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email_source', sa.Enum('GENERATED', 'HUMAN', name='emailsource'), nullable=False),
    sa.Column('classifier_verdict', sa.Enum('PHISHING', 'LEGITIMATE', name='emaillabel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email_source', sa.Enum('GENERATED', 'HUMAN', name='emailsource'), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('persuasion_score', sa.Float(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Enum('PHISHING', 'LEGITIMATE', name='emaillabel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('PASSWORD_RESET', 'INVOICE', 'IT_ALERT', name='scenariotype'), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('urgency_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tactic_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email_source', sa.Enum('GENERATED', 'HUMAN', name='emailsource'), nullable=False),
    sa.Column('tactic_type', sa.Enum('URGENCY', 'AUTHORITY', 'SCARCITY', 'FEAR', 'CURIOSITY', 'OTHER', name='tactictype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_emails')
    op.drop_table('tactic_labels')
    op.drop_table('scenarios')
    op.drop_table('human_emails')
    op.drop_table('eval_scores')
    op.drop_table('detection_results')
    # ### end Alembic commands ###
